[registries.crates-io]
protocol = "sparse"

[target.armv7-unknown-linux-gnueabihf]
linker = "/home/kuba/virt/raspberrypi/toolchains/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"
rustflags = [
	"-C", "link-arg=--sysroot=/home/kuba/virt/raspberrypi/sysroot",
	"-C", "link-arg=-B/home/kuba/virt/raspberrypi/sysroot/usr/lib/arm-linux-gnueabihf",
	"-C", "link-arg=-Wl,-rpath-link,/home/kuba/virt/raspberrypi/sysroot/usr/lib",
	"-C", "link-arg=-Wl,-rpath-link,/home/kuba/virt/raspberrypi/sysroot/usr/lib/arm-linux-gnueabihf",
	"-C", "target-cpu=cortex-a9",
	"-C", "target-feature=+v7,+neon",
]

[target.aarch64-unknown-linux-gnu]
linker = "/home/kuba/virt/raspberrypi/toolchains/gcc-linaro-6.5.0-2018.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc"
rustflags = [
	"-C", "link-arg=--sysroot=/home/kuba/virt/raspberrypi/sysroot",
	"-C", "link-arg=-B/home/kuba/virt/raspberrypi/sysroot/usr/lib/aarch64-linux-gnu",
	"-C", "link-arg=-Wl,-rpath-link,/home/kuba/virt/raspberrypi/sysroot/usr/lib",
	"-C", "link-arg=-Wl,-rpath-link,/home/kuba/virt/raspberrypi/sysroot/usr/lib/aarch64-linux-gnu",
	"-C", "target-cpu=cortex-a72",
	"-C", "target-feature=+neon",
]
