--disable-pinch
--ozone-platform-hint=auto
--enable-features=NativeNotifications,UseOzonePlatform,PrimarySelectionWayland,VaapiVideoDecoder,CanvasOopRasterization,AcceleratedVideoDecodeLinuxZeroCopyGL
--disable-features=MiddleClickAutoscroll,UseChromeOSDirectVideoDecoder
--disable-smooth-scrolling 
--enable-font-antialiasing
--font-render-hinting=slight
--enable-zero-copy
--enable-gpu-rasterization
--ignore-gpu-blocklist
--disable-brave-wallet
--disable-brave-rewards-extension
--password-store=basic
--disable-save-password-bubble
--simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'
