[style.description]
underline = false
bold = false
italic = false

[style.command_name]
underline = false
bold = true
italic = false

[style.example_code]
underline = false
bold = false
italic = false

[style.example_text]
foreground = { ansi = 74 }
underline = false
bold = true
italic = false

[style.example_variable]
foreground = { ansi = 146 }
underline = true
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = false
auto_update_interval_hours = 720
