wireplumber.components = [
  {
    name = node/limit-speaker-volume.lua, type = script/lua
    provides = custom.limit-speaker-volume
  }
]

wireplumber.profiles = {
  main = {
    custom.limit-speaker-volume = required
  }
}
