# Give the built-in ALSA nodes stable, machine-independent names.

monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.pci-0000_c3_00.6.analog-stereo" }
    ]
    actions = {
      update-props = {
        node.name        = "internal-speakers"
        node.description = "Internal Speakers"
        node.nick        = "Speakers"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_input.pci-0000_c3_00.6.analog-stereo" }
    ]
    actions = {
      update-props = {
        node.name        = "internal-mic"
        node.description = "Internal Microphone"
        node.nick        = "Microphone"
      }
    }
  }
]
