[theme]
theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
path = "/"
info_type = "free"
format = " $icon $available"
alert = 10.0
warning = 20.0

[[block]]
block = "disk_space"
path = "/home"
info_type = "free"
format = " $icon $available"
alert = 10.0
warning = 20.0

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization $frequency"

[[block]]
block = "memory"
format = " $icon $mem_used"
interval = 10
warning_mem = 80
critical_mem = 95

[[block]]
block = "backlight"

[[block]]
block = "temperature"
interval = 10
format = " $icon $average"
good = 35
idle = 45
info = 60
warning = 80
chip = "coretemp-isa-*"

[[block]]
block = "net"
format = " $icon {$ssid|} ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "

[[block]]
block = "bluetooth"
mac = "28:F5:37:88:3C:02"
format = "  1More $percentage "
disconnected_format = ""

[[block]]
block = "bluetooth"
mac = "74:5C:4B:D0:02:5B"
format = "  Jabra $percentage "
disconnected_format = ""

[[block]]
block = "bluetooth"
mac = "AC:12:2F:E3:93:59"
format = "  Q35 {$percentage|} "
disconnected_format = ""

[[block]]
block = "bluetooth"
mac = "80:99:E7:4D:52:DD"
format = "  XM4 {$percentage|} "
disconnected_format = ""

[[block]]
block = "sound"
driver = "auto"
device_kind = "sink"
format = " $icon { $volume|} $output_name"
show_volume_when_muted = false
headphones_indicator = true

[block.mappings]
#"alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "💻"
"alsa_output.pci-0000_00_1b.0.3.analog-stereo" = "💻"
"alsa_output.pci-0000_00_1b.0.5.analog-stereo" = "💻" 
"bluez_output.28_F5_37_88_3C_02.a2dp-sink" = ""
"bluez_output.28_F5_37_88_3C_02.1" = ""
#"bluez_output.28_F5_37_88_3C_02.headset-head-unit" = "1 "
"bluez_output.74_5C_4B_D0_02_5B.a2dp-sink" = ""
"bluez_output.74_5C_4B_D0_02_5B.1" = ""
"bluez_output.AC_12_2F_E3_93_59.a2dp-sink" = ""
"bluez_output.AC_12_2F_E3_93_59.1" = ""
"bluez_output.80_99_E7_4D_52_DD.a2dp-sink" = ""
"bluez_output.80_99_E7_4D_52_DD.1" = ""
#"bluez_output.80_99_E7_4D_52_DD.headset-head-unit" = "1 "

#[[block]]
#block = "sound"
#driver = "auto"
#device_kind = "source"
#format = " $icon { $volume|}"
#show_volume_when_muted = false
#headphones_indicator = false

#[block.mappings]
#"alsa_input.pci-0000_00_1b.0.analog-stereo" = "󱡬"
#"rnnoise_source" = "󰍮"

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
info = 80
good = 60
warning = 30
critical = 10
full_threshold = 95
empty_threshold = 5

[[block]]
block = "weather"
format = " $icon $location {$temp}C"
service = { name = "openweathermap", city_id = "764849", units = "metric" }
autolocate = false
interval = 3600

[[block]]
block = "time"
interval = 10
format = " $icon $timestamp.datetime(f:'<b>%d-%m-%Y %R</b>', l:pl_PL)"
